/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simulation;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import utils.CardSwitcher;

/**
 *
 * @author emmabian
 */
public class IntroPanel extends javax.swing.JPanel {

    CardSwitcher switcher = null;
    Timer t = new Timer(125, new IntroPanel.TimerTick());
    protected final Sprite[] pacman = {new Sprite(100,250,"/Users/emmabian/NetBeansProjects/simulation-gui-emma-bian/src/pacman/pacman0.png",320,200), 
        new Sprite(100,250,"/Users/emmabian/NetBeansProjects/simulation-gui-emma-bian/src/pacman/pacman1.png",320,200), 
        new Sprite(100,250,"/Users/emmabian/NetBeansProjects/simulation-gui-emma-bian/src/pacman/pacman2.png",320,200), 
        new Sprite(100,250,"/Users/emmabian/NetBeansProjects/simulation-gui-emma-bian/src/pacman/pacman3.png",320,200), 
        new Sprite(100,250,"/Users/emmabian/NetBeansProjects/simulation-gui-emma-bian/src/pacman/pacman4.png",320,200), 
        new Sprite(100,250,"/Users/emmabian/NetBeansProjects/simulation-gui-emma-bian/src/pacman/pacman5.png",320,200), 
        new Sprite(100,250,"/Users/emmabian/NetBeansProjects/simulation-gui-emma-bian/src/pacman/pacman6.png",320,200), 
        new Sprite(100,250,"/Users/emmabian/NetBeansProjects/simulation-gui-emma-bian/src/pacman/pacman7.png",320,200), 
        new Sprite(100,250,"/Users/emmabian/NetBeansProjects/simulation-gui-emma-bian/src/pacman/pacman8.png",320,200)};

    
    int count = 0;
    
    /**
     * Creates new form IntroPanel
     */
    public IntroPanel(CardSwitcher p) {
        initComponents();
        switcher = p;
        t.start();
    }
    
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        pacman[count].draw(g);
        
    }

    private class TimerTick implements ActionListener {

        public void actionPerformed(ActionEvent ae) {
            if (count < 8) {
                count++;
            } else if (count == 8) {
                count = 0;
            }
            
            repaint();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        infoButton = new javax.swing.JButton();
        simButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Predator and Prey Simulation");

        infoButton.setText("About");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        simButton.setText("Simulator");
        simButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(simButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(infoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simButton)
                .addContainerGap(360, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        switcher.switchToCard("info");
    }//GEN-LAST:event_infoButtonActionPerformed

    private void simButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simButtonActionPerformed
        switcher.switchToCard("simulation");
    }//GEN-LAST:event_simButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton simButton;
    // End of variables declaration//GEN-END:variables
}
